// <auto-generated />
using BossAzAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BossAzAPI.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20230411113542_addPhone")]
    partial class addPhone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BossAzAPI.Entities.EnumKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EnumKeys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "gender"
                        },
                        new
                        {
                            Id = 2,
                            Key = "city"
                        },
                        new
                        {
                            Id = 3,
                            Key = "category"
                        },
                        new
                        {
                            Id = 4,
                            Key = "experience"
                        },
                        new
                        {
                            Id = 5,
                            Key = "education"
                        });
                });

            modelBuilder.Entity("BossAzAPI.Entities.EnumValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KeyId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KeyId");

                    b.ToTable("EnumValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KeyId = 4,
                            Value = "Under 1 year"
                        },
                        new
                        {
                            Id = 2,
                            KeyId = 4,
                            Value = "1 to 3 years"
                        },
                        new
                        {
                            Id = 3,
                            KeyId = 4,
                            Value = "3 to 5 years"
                        },
                        new
                        {
                            Id = 4,
                            KeyId = 4,
                            Value = "More than 5 years"
                        });
                });

            modelBuilder.Entity("BossAzAPI.Entities.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("BossAzAPI.Entities.EnumValue", b =>
                {
                    b.HasOne("BossAzAPI.Entities.EnumKey", "Key")
                        .WithMany()
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Key");
                });
#pragma warning restore 612, 618
        }
    }
}
